[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nf1-3d-organoid-profiling-pipeline"
version = "0.0.1"
description = "Utility modules for the NF1 3D organoid profiling pipeline"
requires-python = ">=3.9"
authors = [{ name = "Michael J. Lippincott" }]
license = { text = "BSD 3-Clause License" }
dependencies = ["tomli"]

[project.optional-dependencies]
dev = ["pytest", "black", "ruff", "pre-commit", "ipykernel"]

[tool.setuptools]
package-dir = { "" = "src" }
py-modules = [
	"animation_utils",
	"arg_parsing_utils",
	"area_size_shape_utils",
	"area_size_shape_utils_gpu",
	"cell_segmentation",
	"colocalization_utils",
	"colocalization_utils_gpu",
	"cp_parallel",
	"file_checking",
	"file_reading",
	"general_segmentation_utils",
	"granularity_utils",
	"intensity_utils",
	"loading_classes",
	"neighbors_utils",
	"notebook_init_utils",
	"nuclei_segmentation",
	"preprocessing_funcs",
	"read_in_channel_mapping",
	"resource_profiling_util",
	"sammed3d_featurizer",
	"segmentation_decoupling",
	"texture_utils",
]

[tool.setuptools.packages.find]
where = ["src"]
include = [
	"featurization_utils*",
	"file_utils*",
	"segmentation_utils*",
	"visualization_utils*",
]
